spring:
  redis:
    cluster:
      nodes: 192.168.3.110:7550,192.168.3.110:7552,192.168.3.110:7553

  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/dbl